# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'My App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for My App

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod "Kingfisher"
pod 'GooglePlaces'
pod 'SDWebImage', '~> 5.0'
pod 'FirebaseUI/Auth'
pod 'Firebase/Storage'
end
